package tui

import (
	"strings"
	"testing"

	tea "github.com/charmbracelet/bubbletea"
)

// TestProviderCatalog_DashboardKeyOpensScreen confirms pressing
// `p` on the dashboard transitions to StateProviderCatalog.
func TestProviderCatalog_DashboardKeyOpensScreen(t *testing.T) {
	t.Parallel()

	m := New(MockOptions(""))
	updated, _ := m.Update(tea.KeyMsg{Type: tea.KeyRunes, Runes: []rune("p")})
	m = updated.(Model)
	if m.state != StateProviderCatalog {
		t.Fatalf("state after 'p' = %v, want StateProviderCatalog", m.state)
	}
}

// TestProviderCatalog_EscReturnsToDashboard mirrors the chrome
// contract: every screen with no destructive flow returns home
// on Esc.
func TestProviderCatalog_EscReturnsToDashboard(t *testing.T) {
	t.Parallel()

	m := New(MockOptions(""))
	mAny, _ := m.Update(tea.KeyMsg{Type: tea.KeyRunes, Runes: []rune("p")})
	m = mAny.(Model)

	mAny, _ = m.Update(tea.KeyMsg{Type: tea.KeyEsc})
	m = mAny.(Model)
	if m.state != StateDashboard {
		t.Fatalf("state after Esc = %v, want StateDashboard", m.state)
	}
}

// TestProviderCatalog_DownArrowAdvancesCursor verifies the row
// cursor walks forwards through the flattened catalog and that
// SelectedID actually changes.
func TestProviderCatalog_DownArrowAdvancesCursor(t *testing.T) {
	t.Parallel()

	m := New(MockOptions(""))
	mAny, _ := m.Update(tea.KeyMsg{Type: tea.KeyRunes, Runes: []rune("p")})
	m = mAny.(Model)

	first := catalogSnapshot(m).SelectedID
	if first == "" {
		t.Skip("registry empty; skipping cursor test")
	}

	mAny, _ = m.Update(tea.KeyMsg{Type: tea.KeyDown})
	m = mAny.(Model)
	second := catalogSnapshot(m).SelectedID
	if second == "" || second == first {
		t.Errorf("cursor did not advance: first=%q second=%q", first, second)
	}
}

// TestProviderCatalog_EnterTogglesDetail flips the deep-dive
// toggle. Two presses toggle on→off→on.
func TestProviderCatalog_EnterTogglesDetail(t *testing.T) {
	t.Parallel()

	m := New(MockOptions(""))
	mAny, _ := m.Update(tea.KeyMsg{Type: tea.KeyRunes, Runes: []rune("p")})
	m = mAny.(Model)

	if m.catalog.ShowDetail {
		t.Fatalf("setup: ShowDetail = %v, want false", m.catalog.ShowDetail)
	}
	mAny, _ = m.Update(tea.KeyMsg{Type: tea.KeyEnter})
	m = mAny.(Model)
	if !m.catalog.ShowDetail {
		t.Fatalf("after Enter: ShowDetail = false, want true")
	}
	mAny, _ = m.Update(tea.KeyMsg{Type: tea.KeyEnter})
	m = mAny.(Model)
	if m.catalog.ShowDetail {
		t.Fatalf("after second Enter: ShowDetail = true, want false")
	}
}

// TestProviderCatalog_CopyBriefingSuccessSetsHint stubs the
// clipboard runner with a no-op success and asserts the model
// reflects the green ack.
func TestProviderCatalog_CopyBriefingSuccessSetsHint(t *testing.T) {
	cleanup := setClipboardCommandRunner(func(_ string, _ ...string) clipboardCommand {
		return &fakeClipboardCommand{}
	})
	t.Cleanup(cleanup)

	m := New(MockOptions(""))
	mAny, _ := m.Update(tea.KeyMsg{Type: tea.KeyRunes, Runes: []rune("p")})
	m = mAny.(Model)

	mAny, _ = m.Update(tea.KeyMsg{Type: tea.KeyRunes, Runes: []rune("c")})
	m = mAny.(Model)
	if !strings.Contains(m.catalog.CopyHint, "copied") {
		t.Errorf("CopyHint after c = %q, want 'copied' substring", m.catalog.CopyHint)
	}
	if !m.catalog.ShowDetail {
		t.Errorf("ShowDetail after c = false, want true (briefing forces detail)")
	}
}

// TestProviderCatalog_CopyBriefingFailureSetsErrorHint stubs the
// clipboard runner to fail so the model surfaces a remediation
// hint without crashing.
func TestProviderCatalog_CopyBriefingFailureSetsErrorHint(t *testing.T) {
	cleanup := setClipboardCommandRunner(func(_ string, _ ...string) clipboardCommand {
		return &fakeClipboardCommand{err: errClipboardUnsupported}
	})
	t.Cleanup(cleanup)

	m := New(MockOptions(""))
	mAny, _ := m.Update(tea.KeyMsg{Type: tea.KeyRunes, Runes: []rune("p")})
	m = mAny.(Model)

	mAny, _ = m.Update(tea.KeyMsg{Type: tea.KeyRunes, Runes: []rune("c")})
	m = mAny.(Model)
	if !strings.Contains(strings.ToLower(m.catalog.CopyHint), "clipboard") {
		t.Errorf("CopyHint after failed copy = %q, want clipboard error substring", m.catalog.CopyHint)
	}
}

// TestProviderCatalog_BriefingComposeContainsRequiredSections
// asserts the plain-text briefing carries every operator-visible
// field the View renders. Used as a regression guard so future
// schema bumps do not silently drop sections.
func TestProviderCatalog_BriefingComposeContainsRequiredSections(t *testing.T) {
	t.Parallel()

	m := New(MockOptions(""))
	mAny, _ := m.Update(tea.KeyMsg{Type: tea.KeyRunes, Runes: []rune("p")})
	m = mAny.(Model)
	mAny, _ = m.Update(tea.KeyMsg{Type: tea.KeyEnter})
	m = mAny.(Model)
	snap := catalogSnapshot(m)
	if snap.Detail.BriefingPlainText == "" {
		t.Skip("registry empty or no preset selected")
	}
	for _, needle := range []string{"Webox Provider Briefing", "id", "panel", "node runtime", "Generated by Webox Provider Catalog"} {
		if !strings.Contains(strings.ToLower(snap.Detail.BriefingPlainText), strings.ToLower(needle)) {
			t.Errorf("briefing missing %q\n--- briefing ---\n%s", needle, snap.Detail.BriefingPlainText)
		}
	}
}

// fakeClipboardCommand is a test-only stub for `clipboardCommand`.
type fakeClipboardCommand struct {
	err   error
	stdin string
}

func (f *fakeClipboardCommand) SetStdin(text string) { f.stdin = text }
func (f *fakeClipboardCommand) Run() error           { return f.err }
