version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: "Europe/Warsaw"
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - go
    groups:
      go-deps:
        update-types:
          - minor
          - patch
    commit-message:
      prefix: "build(deps)"
      include: "scope"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: "Europe/Warsaw"
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - github-actions
    commit-message:
      prefix: "build(ci)"
      include: "scope"
