/**
 * Webox Sprint 20 smoke-test runner.
 *
 * Drives `./bin/webox --mock` through every Sprint 20 user-facing
 * change using tuistory (Playwright-for-terminals). Each scenario is
 * its own module under `scenarios/`; this runner sequences them and
 * writes a markdown report.
 *
 * Usage:
 *
 *   make build && npm --prefix scripts/manual-test run smoke
 *
 * Or via the Makefile wrapper (preferred):
 *
 *   make smoke-test
 *
 * Artefacts:
 *   - docs/screenshots/sprint-20/manual/{NN}-{name}.txt
 *   - docs/screenshots/sprint-20/manual/REPORT.md
 *
 * Exit code 0 = every assertion passed.
 * Exit code 1 = at least one assertion failed (binary path printed
 *               to stderr for triage).
 */

import { existsSync } from "node:fs";
import { writeFile } from "node:fs/promises";
import { join } from "node:path";

import { ARTEFACTS_DIR, WEBOX_BIN } from "./lib.ts";
import { run as runBento } from "./scenarios/bento-modes.ts";
import { run as runHelp } from "./scenarios/help-overlay.ts";
import { run as runCatalog } from "./scenarios/provider-catalog.ts";
import { run as runDetail } from "./scenarios/project-detail.ts";
import { run as runMouse } from "./scenarios/mouse-click.ts";

interface Scenario {
  name: string;
  description: string;
  fn: () => Promise<void>;
}

const SCENARIOS: Scenario[] = [
  {
    name: "bento-modes",
    description: "Resize 160→120→100→60→120 verifies Tiny/Standard/Ultra/UltraPlus.",
    fn: runBento,
  },
  {
    name: "help-overlay",
    description: "Sprint 20 TASK-20.5 ? overlay open/dismiss/strict-block.",
    fn: runHelp,
  },
  {
    name: "provider-catalog",
    description: "Sprint 20 TASK-20.2 p catalog navigation/detail/copy-hint.",
    fn: runCatalog,
  },
  {
    name: "project-detail",
    description: "Sprint 20 TASK-20.4 tab 2/3 unstubbed + Tab back-nav.",
    fn: runDetail,
  },
  {
    name: "mouse-click",
    description: "Sprint 20 TASK-20.1 layout-aware click (drill/back/no-op).",
    fn: runMouse,
  },
];

async function main() {
  if (!existsSync(WEBOX_BIN)) {
    process.stderr.write(
      `webox binary not found at ${WEBOX_BIN} — run \`make build\` first.\n`,
    );
    process.exit(2);
  }

  const startedAt = new Date();
  const results: Array<{ scenario: Scenario; ok: boolean; error?: string }> =
    [];

  for (const scenario of SCENARIOS) {
    const before = process.exitCode ?? 0;
    try {
      await scenario.fn();
      const ok = (process.exitCode ?? 0) === before;
      results.push({ scenario, ok });
    } catch (err) {
      results.push({
        scenario,
        ok: false,
        error: err instanceof Error ? err.message : String(err),
      });
      process.exitCode = 1;
    }
  }

  await writeReport(results, startedAt);
  const failed = results.filter((r) => !r.ok).length;
  if (failed > 0) {
    process.stderr.write(
      `\n✗ ${failed} of ${results.length} scenarios failed. See ${join(ARTEFACTS_DIR, "REPORT.md")}\n`,
    );
    process.exit(1);
  }
  process.stdout.write(
    `\n✓ all ${results.length} scenarios passed. Report: ${join(ARTEFACTS_DIR, "REPORT.md")}\n`,
  );
}

async function writeReport(
  results: Array<{ scenario: Scenario; ok: boolean; error?: string }>,
  startedAt: Date,
) {
  const lines: string[] = [
    "# Sprint 20 — Manual Smoke Tests",
    "",
    `Generated by \`scripts/manual-test/smoke.ts\` (tuistory PTY driver) on \`${startedAt.toISOString()}\`.`,
    "",
    "Every scenario exercises a Sprint 20 user-facing change against `./bin/webox --mock` in a headless PTY. Text snapshots live next to this report as `NN-name.txt`; the markdown table below lists each scenario and its first asserted invariant.",
    "",
    "To re-run locally: `make smoke-test` (requires Node 22+ for `--experimental-strip-types`).",
    "",
    "To see a scenario live: `tuistory attach -s webox-mock` while the runner sleeps, then `Ctrl+C` twice to detach.",
    "",
    "| Scenario | Status | Description | Artefacts |",
    "| --- | --- | --- | --- |",
  ];
  for (const r of results) {
    const status = r.ok ? "✅ pass" : "❌ fail";
    const note = r.error ? ` — ${r.error}` : "";
    lines.push(
      `| \`${r.scenario.name}\` | ${status}${note} | ${r.scenario.description} | see \`*.txt\` snapshots |`,
    );
  }
  lines.push("");
  lines.push(
    "Failed assertions print to stderr in the runner output; consult the snapshot files to triage. Snapshots are diff-friendly so a `git diff docs/screenshots/sprint-20/manual/` highlights regressions between runs.",
  );
  await writeFile(join(ARTEFACTS_DIR, "REPORT.md"), lines.join("\n") + "\n");
}

await main();
